baseURL = "https://danielgospodinow.com/"
languageCode = "en-us"
title = "Daniel Gospodinow"
theme = "minimal"

[params]
    author = "Daniel Gospodinow"
    profilePic = "https://i.imgur.com/2qfesGo.jpg"
    description = ""
    githubUsername = "danielgospodinow"
    accent = "#407ba8"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "https://medium.com/@danielgospodinow"
    name = "Blog"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://www.facebook.com/DanielGospodinow"
    name = "facebook"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/danielgospodinow/"
    name = "instagram"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/dgospodinow/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/danielgospodinow/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://github.com/danielgospodinow/"
    name = "github"
    weight = 5

[[menu.icon]]
    url = "https://medium.com/@danielgospodinow"
    name = "medium"
    weight = 6

[[menu.icon]]
    url = "mailto:danielgospodinow@gmail.com"
    name = "envelope-o"
    weight = 7
